### ISSUE TITLE
This is broken with Docker 17.12.0-ce

### ISSUE THREAD

**Issue by RobCannon** [merofeev/docker-windows-volume-watcher#7]
After upgrading to Docker 17.12.0-ce, I see these warnings and files changes are no longer picked up by docker:

WARNING:root:Bind of container environmentrefreshapp_environmentrefresh_1 was skipped since it has invalid source path /host_mnt/c/Projects/Foundation/EnvironmentRefreshApp/server/Main
WARNING:root:Bind of container environmentrefreshapp_environmentrefresh_1 was skipped since it has invalid source path /host_mnt/c/Projects/Foundation/EnvironmentRefreshApp/server/Controllers
WARNING:root:Bind of container environmentrefreshapp_environmentrefresh_1 was skipped since it has invalid source path /host_mnt/c/Projects/Foundation/EnvironmentRefreshApp/client/src
WARNING:root:Bind of container environmentrefreshapp_environmentrefresh_1 was skipped since it has invalid source path /host_mnt/c/Projects/Foundation/EnvironmentRefreshApp/client/e2e
WARNING:root:Bind of container environmentrefreshapp_environmentrefresh_1 was skipped since it has invalid source path /host_mnt/c/Projects/Foundation/EnvironmentRefreshApp/server/Models
WARNING:root:No mounts match container name pattern * and host directory pattern c:\Projects\Foundation\EnvironmentRefreshApp

**Comment by merofeev** [comment]
Hi @RobCannon,
I believe this issue should be fixed by #6 PR which we merged recently. Could you please make sure that you are using the 1.0.7 version of docker-windows-volume-watcher (e.g. pip show docker-windows-volume-watcher).

**Comment by RobCannon** [comment]
Your are right it is fixed.  I tried a pip install, but it did not update.  I uninstalled and reinstalled and it is working correctly now.  Thanks.
